[package]
name = "tauler-ui-macro"
description = "Proc macro for declaring tauler UI components with JSX-like syntax"
keywords = ["tauler", "statusbar", "jsx", "macro"]
categories = ["development-tools::procedural-macro-helpers", "gui"]
readme = "README.md"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
rstml = "0.13.0"
syn = { version = "3.0.3", features = ["full"] }
quote = "1.0.47"
proc-macro2 = "1.0.107"
